#pragma once

#define TAPPING_TERM 275
#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

#define LED_CAPS_LOCK_PIN RXLED

#define VIAL_KEYBOARD_UID {0xD5, 0x58, 0x0E, 0x82, 0x40, 0xE2, 0xEA, 0x63}
