#pragma once

#define TAPPING_TERM 275
#define TAPPING_TERM_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

#define LED_CAPS_LOCK_PIN RXLED

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
